apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka
  annotations:
    github.com/project-slug: wetestroadie/kafka
spec:
  type: other
  lifecycle: unknown
  owner: wetestroadie/team-b
